### ISSUE TITLE
Consider being asynchronous

### ISSUE THREAD

**Issue by ghost** [weblocks-framework/weblocks#2]
Almost all modern web frameworks are based on the event-loop model(Boost.Asio, Node.js, [Amp](http://amphp.org/), etc), so that non-blocking, async I/O can be used to improve performance and increace concurrency.
I've discovered an async library for common lisp which uses libuv at low level.
https://github.com/orthecreedence/cl-async
Consider using it in weblocks.

**Comment by anquegi** [comment]
I believe that hunchentoot should be replaced by Clack. Then you can easily change webserbers like hunchentoot, woo (libev), Wookiee  (cl-adync) or fastcgi. But can this be posible?

**Comment by html** [comment]
Yes, hunchentoot should be replaced by Clack. One developer does some steps in that way but I don't know at what stage is it.

**Comment by anquegi** [comment]
the steps, that you mention @html are in a separate branch, maybe I can help (Well I'm learning lisp now) but this could be an very very interesting project
